import pygame


class Screen:

    # CANVAS SURFACE
    GameScreenDummySurface: pygame.Surface = None

    # SCREEN ITSELF
    DUMMY_SCREEN_WIDTH = 1280
    DUMMY_SCREEN_HEIGHT = 720
    HALF_SCREEN_WIDTH = DUMMY_SCREEN_WIDTH // 2
    HALF_SCREEN_HEIGHT = DUMMY_SCREEN_HEIGHT // 2

    _REFERENCE_RESOLUTION_WIDTH = 1280
    _REFERENCE_RESOLUTION_HEIGHT = 720
    SCALE_FROM_REFERENCE = ((DUMMY_SCREEN_HEIGHT * 100) / _REFERENCE_RESOLUTION_HEIGHT / 100)

    TILE_SIZE = 64